"""Pydantic models for the Chest X-ray caption drafting API."""

from typing import Optional

from pydantic import BaseModel, Field


class CaptionResponse(BaseModel):
    """Response returned for a single captioned image."""

    caption: str = Field(..., description="AI-drafted caption. Not a clinical finding.")
    model_id: str = Field(..., description="Base model + adapter identifier used.")
    generation_time_ms: float = Field(..., description="Wall-clock time for generation, in ms.")
    disclaimer: str = Field(
        default=(
            "This caption is generated by a research-stage model and has NOT been "
            "reviewed by a clinician. It is not a diagnosis and must not be used "
            "for clinical decision-making."
        )
    )


class HealthResponse(BaseModel):
    """Response for the /health endpoint."""

    status: str
    model_loaded: bool
    base_model: str
    adapter_path: str
    device: str
    detail: Optional[str] = None
